global:

route:
  receiver: telegram
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "enter_your_bot_token_here"
        chat_id: 389594576
        api_url: "https://api.telegram.org"
        parse_mode: HTML
        send_resolved: true

        message: |

            {{ if eq .Status "firing" }}
            <b>Avi's Monitoring Stack</b>
            ______________________________

            <b> Infrastructure Alert </b> ⚠️

            <b>Alert:</b> {{ .CommonLabels.alertname }}
            <b>Status:</b> FIRING 🔴 
            <b>Severity:</b> {{ .CommonLabels.severity }} ⚠️
            <b>Job:</b> {{ (index .Alerts 0).Labels.job }}
            <b>Instance:</b> {{ (index .Alerts 0).Labels.instance }}
            <b>Summary:</b>
            {{ .CommonAnnotations.summary }}
            <b>Description:</b>
            {{ .CommonAnnotations.description }}

            <b>Triggered:</b> {{ (index .Alerts 0).StartsAt.Local.Format "02 Jan 2006 15:04:05" }}
            ______________________________

            {{ else }}

            <b>Avi's Monitoring Stack</b>
            ______________________________

            <b> {{ .CommonLabels.alertname }} Recovered </b> ✅ 
        
            <b>Alert:</b> {{ .CommonLabels.alertname }}
            <b>Status:</b> RESOLVED 🟢 
            <b>Job:</b> {{ (index .Alerts 0).Labels.job }}
            <b>Instance:</b> {{ (index .Alerts 0).Labels.instance }}
            <b>Description:</b>
            The monitored service has recovered successfully.

            <b>Recovered:</b> {{ (index .Alerts 0).EndsAt.Local.Format "02 Jan 2006 15:04:05" }}
            ______________________________

            {{ end }}
          
