global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mongodb
    static_configs:
      - targets:
          - 'mongo-exporter:9216'
  
  - job_name: windows
    static_configs:
      - targets:
          - 'host.docker.internal:9182'

# alertmanager configuration
alerting:
  alertmanagers:
   - static_configs:
       - targets:
           - alertmanager:9093

rule_files:
  - alerts.yml


